### ISSUE TITLE
Make wand::get_content_type free from guess_content_type or a new function..

### ISSUE THREAD

**Issue by bedantaguru** [hrbrmstr/filemagic#4]
**[Feature request]**

If possible make `get_content_type` independent from `guess_content_type`. Which I mean that `get_content_type` should only perform magic number based detection and will simply say let say '???' (that can be changed) for unknown types.

This is a specific indication to the user that magic number based detection has returned unknown file type. What is happening now is that a csv file wrongly saved as docx is returned as docx file. Reason being csv files are not binary and all magic number checks failed to detect it but `guess_content_type` is determining it as docx.

Here is the reproducible example 
```r
wand::get_content_type(system.file("extdata", "messy", "csv.docx", package = "tidycells", mustWork = TRUE))
```

**Comment by bedantaguru** [comment]
BTW which one is in active development 
this repo or https://gitlab.com/hrbrmstr/wand

**Comment by hrbrmstr** [comment]
many thanks for using the pkg and taking the time to file an issue!

I added a logical `guess` parameter to control whether it fails out to the guess function or not.

Issues & PRs are welcome & tracked across:

- https://git.rud.is/hrbrmstr/wand.git
- https://git.sr.ht/~hrbrmstr/wand
- https://gitlab.com/hrbrmstr/wand
- https://bitbucket.com/hrbrmstr/wand
- https://github.com/hrbrmstr/wand

since GitHub should not be what it has become.
